config/routes.rb
Rails.application.routes.draw do
  # get 'comments/new'
  # get 'comments/show'
  resources :topics do
    resources :comments, only: [:create, :show, :destroy]
  end

  resources :likes, only: [:create, :destroy]
  devise_for :users

  root 'topics#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  belongs_to :parent, class_name: "Comment", optional: true

  # child comment
  has_many :comments, foreign_key: :parent_id
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: {scope: :topic_id}
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :topics
        has_many :comments
        has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end


  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.create(comment_params)

    if @comment.save
      redirect_to topic_path(@topic)

    else
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end
  end

  def show
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :topic_id, :user_id, :parent_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @like = current_user.likes.new(like_params)

        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end

        redirect_to @like.topic

    end

    def destroy
        @like = current_user.likes.find(params[:id])
        topic = @like.topic
        @like.destroy
        redirect_to @like.topic        
    end

    def like_params
        params.require(:like).permit(:topic_id)
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
    # @topic = Topic.find(params[:id])
    @comments = @topic.comments.where(parent_id: nil).includes(:user)
    # = render @topic.comments
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.haml
%div
  %p= comment.content
  %small by #{comment.user.email}
  %a{href: "#", class: "comment-form-display"}Reply
  .comment-form
    = render partial: 'comments/form', locals: {topic: comment.topic, parent: comment}
  %hr  
  .sub-comment
    = render partial: comment.comments

:javascript
  document.querySelectorAll('.comment-form-display').forEach((el)=>
    el.addEventListener('click', (ev)=>{
      ev.preventDefault();
      el.nextElementSibling.style="display: block;"
    })
  )

app/views/comments/_form.html.haml
%form{action: "#{topic_comments_path(topic)}", method: "post"}
  %input{type: "hidden", name: "authenticity_token", value: form_authenticity_token}
  
  - if parent.present?
    %input{type: "hidden", name: "comment[parent_id]", value: "#{parent.id}"}

  %textarea{name: "comment[content]", rows: "8", cols: "40"}
  %input{name: "comment[user_id]", type: "hidden", value: "#{current_user.id if current_user.present?}"}

  %input{type: "submit", value: "Submit"}

app/views/comments/new.html.haml
%h1 Comments#new
%p Find me in app/views/comments/new.html.erb

app/views/comments/show.html.haml
%h1 Comments#show
%p Find me in app/views/comments/show.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MessageBoardApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    %nav.navbar.navbar-expand-sm.bg-dark.navbar-dark
      / Brand/logo
      = link_to 'Message Board', topics_path, :class => "navbar-brand"
      - if user_signed_in?
        = link_to 'New Topic', new_topic_path
      / Links
      %ul.navbar-nav.ml-auto
        %li.nav-item
          - if user_signed_in?
            = link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            = link_to "Sign In", new_user_session_path
            = link_to "Sign Up", new_user_registration_path


    = yield

app/views/topics/_form.html.haml
.container
  %h2 Create New Topic
  = form_with(model: topic) do |form|
    .form-group
      %label{for: "email"} Email:
      = form.text_field :title, :class => "form-control", :placeholder => "Enter email"
    .form-group
      %label{for: "content"} Content:
      = form.text_field :content, :class => "form-control", :placeholder => "Enter your content"
    = form.hidden_field :user_id, value: current_user.id
    = form.submit
    = link_to 'Back', topics_path

app/views/topics/edit.html.haml
%h1 Editing Topic
= render 'form', topic: @topic
= link_to 'Show', @topic
|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
.container
  %h2 Card Header and Footer
  - @topics.each do |topic|
    .card
      .card-header
        %h4= topic.title
        
      .card-body
        %p= topic.content
      .card-footer
        %p= topic.user.email
      .card-body
        = link_to 'Show', topic
        - if current_user == topic.user
          %td= link_to 'Edit', edit_topic_path(topic)
          %td= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }
    %br

app/views/topics/new.html.haml
%h1 New Topic
= render 'form', topic: @topic

app/views/topics/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @topic.title
%p
  %strong Content:
  = @topic.content
%p
  %strong User:
  = @topic.user.email
= link_to 'Edit', edit_topic_path(@topic)
|
= link_to 'Back', topics_path

= @topic.likes.count
- like = current_user.likes.find_by(topic: @topic)
-if like.nil?
  %form{action: "/likes", method: "post"}
    %input{name: "authenticity_token", type: "hidden", value: form_authenticity_token}
    %input{name: "like[topic_id]", type: "hidden", value: "#{@topic.id}"}
    %input{type: "submit", value: "Like"}
- else
  %form{action: "#{like_path(like)}", method: "post"}
    %input{name: "authenticity_token", type: "hidden", value: form_authenticity_token}
    %input{type: "hidden", name: "_method", value: "DELETE"}

    %input{type: "submit", value: "Unlike"}

%h3 Comments:
-#= form_for([@topic, Comment.new]) do |f|
  -#= f.text_area :content
  -#= f.hidden_field :user_id, value: current_user.id if current_user.present?
  -#= f.submit
= render partial: 'comments/form', locals: {topic: @topic, parent: nil}
= render partial: 'comments/comment', collection: @comments.order(id: :desc), :as => :comment